### ISSUE TITLE
pages build and deployment failed

### ISSUE THREAD

**Issue by bingbing1263** [KraHsu/HsuBlog#4]
<img width="251" alt="image" src="https://github.com/KraHsu/HsuBlog/assets/30209457/11085b5e-d488-437e-b33a-3c783400b2bb">

ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid YAML front matter in /github/workspace/src/components/footer/Footer.astro

**Comment by KraHsu** [comment]
Is there a default build error? If yes, can you give more information, such as Footer.astro?
Of course, if you have changed "Footer.astro" please check your Frontmatter.

**Comment by bingbing1263** [comment]
没有改动。直接出现报错了。

**Comment by KraHsu** [comment]
这似乎并不是HsuBlog带来的报错，可以参考[Invalid YAML front matter in](https://github.com/withastro/astro/issues/6830)
