### ISSUE TITLE
Should We turn this to a Template?

### ISSUE THREAD

**Issue by david-wei-01001** [KraHsu/HsuBlog#6]
Hi there,
I think this repo is amazing!
Thank you very much for creating this piece of artwork!

But do you want to turn it into a template?
Navigate to your GitHub repository in your web browser.
Click on the repository's "Settings" tab.
Scroll down to the "Options" section.
Look for the "Repository template" section. You should see a checkbox labeled "Template repository."
Check this box to make your repository a template repository.
Once you've checked this box, scroll down to the bottom of the page and click the "Save changes" button.
And a Use this template button will appear :)

Also, I highly suggest to build a gh-pages branch so that people can deploy it directly through Github Pages

**Comment by KraHsu** [comment]
Thank you so much for your kind words and for taking the time to provide such valuable suggestions!  I’m thrilled to hear that you find the repository valuable.

Best regards,

[KraHsu]
